
"""Central state object flowing through the pipeline."""

from dataclasses import dataclass, field
from typing import Optional
from ..core.torch_compat import torch

from .camera import Camera
from .mesh import MeshData
from .textures import TextureData


@dataclass
class View:
    """One canonical image view and its camera."""

    image_tensor: torch.Tensor
    camera: Camera

    def __post_init__(self) -> None:
        if not isinstance(self.image_tensor, torch.Tensor) or self.image_tensor.ndim != 3:
            raise ValueError("image_tensor must be a torch Tensor shaped (C, H, W)")


@dataclass
class GeometryState:
    """Geometry generated by reconstruction stages."""

    raw_mesh: Optional[MeshData] = None

    def set_raw_mesh(self, mesh: MeshData) -> None:
        """Set the reconstructed mesh."""
        self.raw_mesh = mesh


@dataclass
class Scene:
    """Mutable, state-driven scene passed between pipeline stages."""

    primary_image: Optional[torch.Tensor] = None
    source_image_path: Optional[str] = None
    output_path: Optional[str] = None
    views: list[View] = field(default_factory=list)
    geometry: GeometryState = field(default_factory=GeometryState)
    textures: TextureData = field(default_factory=TextureData)
    diagnostics: dict[str, object] = field(default_factory=dict)


